### ISSUE TITLE
Cannot install theme for Textmate 2

### ISSUE THREAD

**Issue by ashishwadekar** [dracula/textmate#3]
When trying to install theme getting an error :
The bundle " Dracula " could not be installed because it is malformed - the bundle lacks mandatory keys in its property list.
What is missing in the installation process?

**Comment by priyansh71** [comment]
It is working now, clone the repo and open the **Dracula.tmTheme** file using the Textmate application bundles.
Then close the application, open it again  go to View, dark mode and choose the theme Dracula.
